CREATE TABLE clientes (
	id SERIAL PRIMARY KEY,
	dni VARCHAR(8) UNIQUE NOT NULL,
	nombre VARCHAR(255) UNIQUE NOT NULL,
	apellido VARCHAR(255) NOT NULL,
	telefono VARCHAR(9) UNIQUE NOT NULL
);

CREATE TABLE mascotas (
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
	edad INT NOT NULL,
	cliente_id INT NOT NULL,
	FOREIGN KEY (cliente_id) REFERENCES clientes(id)
	ON DELETE CASCADE
    ON UPDATE CASCADE
);
